### ISSUE TITLE
More AUR support suggestions

### ISSUE THREAD

**Issue by witt-bit** [claui/vscode-aur-packaging#38]
Can provide richer functions for AUR workspace.
1.Provides file type association for .SRCINFO files
2.Provides convenient operation functions, such as updpkgsums command, and graphical buttons for executing makepkg --printsrcinfo > .SRCINFO command to generate .SRCINFO file
3.Provides run options, such as makepkg -si installation, clean workspace, etc.
4.Quickly create an empty AUR package repository with a sample PKGBUILD file

This extension is an excellent idea and needs to be continuously improved.

**Comment by claui** [comment]
Thanks @witt-bit for the suggestions.

> 1.Provides file type association for .SRCINFO files

Opened as separate issue #39.

> 2.Provides convenient operation functions, such as updpkgsums command, and graphical buttons for executing makepkg --printsrcinfo > .SRCINFO command to generate .SRCINFO file

Opened as separate issue #40.

> 3.Provides run options, such as makepkg -si installation, clean workspace, etc.

Opened as separate issue #41.

> 4.Quickly create an empty AUR package repository with a sample PKGBUILD file

I’m already maintaining a Cookiecutter template for that, [cookiecutter-pkgbuild](https://github.com/claui/cookiecutter-pkgbuild).

If you think it makes sense to integrate the Cookiecutter template with the VS Code extension, feel free to open a separate issue. I don’t think it’s a good fit, because VS Code is workspace-/folder oriented, and scaffolding templates generally work best if the workspace root doesn’t exist yet.

A simpler variant of this may be for the extension to contribute a snippet, which can be inserted into an empty PKGBUILD via the `Snippets: Insert snippet` command.

> This extension is an excellent idea and needs to be continuously improved.

Thank you for your honest feedback.  
Contributions are always welcome.
